language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - build-tools-28.0.3
    - android-28
    - android-22
    - android-27
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

before_script:
  - yes | sdkmanager "platforms;android-28"
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - export PROPERTIES="
    -Porg.w3.telemesh=${artifactory_app_key}
    -Prightmesh_build_username=${rightmesh_build_username}
    -Prightmesh_build_password=${rightmesh_build_password}"
  - chmod +x ./gradlew

script: ./gradlew viper:build $PROPERTIES